name:                messageboard-server
version:             0.1.0.0
github:              "timbod7/adl-demo"
license:             BSD3
author:              "Tim Docker"
maintainer:          "tim@dockerz.net"
copyright:           "2020 Tim Docker"

description:         Please see the README on GitHub at <https://github.com/timbod7/adl-demo>

dependencies:
- base >= 4.7 && < 5
- aeson >= 1.4 && < 1.5
- bytestring >= 0.10.8 && < 0.11
- base64-bytestring >= 1.0 && < 1.1
- containers >= 0.6 && < 0.7
- jwt >= 0.10 && < 0.11
- http-types >= 0.12 && < 0.13
- Spock >= 0.13.0.0 && < 0.14
- password >= 1.0 && < 1.1
- scientific >= 0.3 && < 0.4
- stm >= 2.5 && < 3.0
- time >= 1.8 && < 1.9
- text >= 1.2 && < 1.3
- vector >= 0.12 && < 0.13
- unordered-containers >= 0.2 && < 0.3
- yaml >= 0.11 && < 0.12




library:
  source-dirs: src

executables:
  messageboard-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - messageboard-server
